services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./glance.yml:/app/glance.yml
      - ./assets:/app/assets
      - /etc/TZ:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  it-tools:
    image: 'ghcr.io/corentinth/it-tools:latest'
    ports:
      - '8081:80'
    restart: unless-stopped
    container_name: it-tools
  # cyberchef:
  #   image: 'ghcr.io/gchq/cyberchef:latest'
  #   ports:
  #       - '8181:80'
  #   tty: true
  #   stdin_open: true