http:
  # Add the router
  routers:
    traefik-dashboard:
      entryPoints:
      - web
      - web-secure
      service: dashboard@internal
      rule: "Host(`apps.localhost`)"
    traefik-dashboard-api:
      entryPoints:
      - web
      - web-secure
      service: api@internal
      rule: "Host(`apps.localhost`) && PathPrefix(`/api`)"
