http:
  routers:
    glance:
      entryPoints:
        - web
      rule: "Host(`glance.localhost`) || HostRegexp(`glance.localhost/.*`)"
      service: "glance-service"
    it-tools:
      entryPoints:
        - web
      rule: "Host(`it-tools.localhost`)"
      service: "it-tools-service"

  services:
    glance-service:
      loadBalancer:
        servers:
        - url: "http://glance"
    it-tools-service:
      loadBalancer:
        servers:
        - url: "http://it-tools"