server:
  port: 8080
  assets-path: /app/assets

theme:
  background-color: 225 14 15
  primary-color: 157 47 65
  contrast-multiplier: 1.1

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar

          - type: clock
            hour-format: 24h
            timezones:
              - timezone: Asia/Taipei
                label: Taipei
              - timezone: Asia/Tokyo
                label: Tokyo
              - timezone: America/New_York
                label: New York
              - timezone: Europe/London
                label: London
              - timezone: Europe/Berlin
                label: Berlin

          - type: bookmarks
            groups:
              - title: Google
                links:
                - title: Google Sheet
                  url: https://docs.google.com/spreadsheets/u/0/
                  icon: si:googlesheets
              - title: 開發者工具
                links:
                - title: IT Tools
                  url: http://it-tools.localhost/
                  icon: https://github.com/CorentinTh/it-tools/blob/main/public/android-chrome-512x512.png?raw=true
              - title: AI 工具
                color: 10 70 50
                links:
                - title: ChatGPT
                  url: https://openai.com/chatgpt/
                  icon: si:openai
                - title: Perplexity
                  url: https://www.perplexity.ai/
                  icon: si:perplexity
                - title: claude.ai
                  url: https://claude.ai/
                  icon: si:anthropic
                - title: Leonardo AI
                  url: https://leonardo.ai/
                  icon: assets/leonardo-ai.webp
                - title: v0
                  url: https://v0.dev/
                  icon: si:vercel
          
          - type: monitor
            cache: 1m
            title: Services
            sites:
            - title: Vaultwarden
              url: https://vault.madaowebsite.com/
              icon: si:vaultwarden
              allow-insecure: true

      - size: full
        widgets:
          - type: search
            search-engine: google
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}

          - type: hacker-news

          - type: videos
            channels:
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCv6J_jJa8GJqFwQNgNrMuww # ServeTheHome
              - UCOk-gHyjcWZNj3Br4oxwh0A # Techno Tim

          - type: reddit
            subreddit: selfhosted

      - size: small
        widgets:
          - type: weather
            location: Taichang, Taiwan
            hour-format: 24h
            show-area-name: true

          - type: stocks
            stocks:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft
              - symbol: GOOGL
                name: Google
              - symbol: AMD
                name: AMD
              - symbol: RDDT
                name: Reddit
    
  - name: Development
    columns:
    - size: small
      widgets:
        - type: rss
          limit: 500
          title: Github Daily Trending
          collapse-after: 5
          style: vertical-cards
          feeds:
            - url: https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml
              title: Github Daily Trending All
        - type: bookmarks
          groups:
            - title: Platform
              links:
              - title: GCP
                url: https://console.cloud.google.com/
                icon: si:googlecloud
              - title: AWS
                url: https://aws.amazon.com/
                icon: si:amazonwebservices
            - title: Database
              links:
              - title: MongoDB
                url: https://www.mongodb.com/
                icon: si:mongodb
              - title: supabase
                url: https://supabase.com/
                icon: si:supabase
              - title: infisical
                url: https://infisical.com/
                icon: assets/infisical.png
            - title: Deployment
              links:
              - title: Zeabur
                url: https://zeabur.com/
                icon: https://styles.redditmedia.com/t5_az73n5/styles/communityIcon_wsc9jjd6elnc1.png
            - title: Learn
              links:
              - title: Project Based Learning
                links: https://github.com/practical-tutorials/project-based-learning
              - title: Rust Course
                url: https://course.rs/about-book.html
                icon: si:rust
              - title: Go with Tests
                url: https://quii.gitbook.io/learn-go-with-tests
                icon: si:go
            
    - size: full
      widgets:
      - type: videos
        style: grid-cards
        collapse-after-rows: 2
        limit: 18
        channels:
          - UCwXdFgeE9KYzlDdR7TG9cMw
      - type: videos
        style: grid-cards
        collapse-after-rows: 2
        limit: 18
        channels:
          - UCmXmlB4-HJytD7wek0Uo97A
      - type: videos
        style: grid-cards
        collapse-after-rows: 2
        limit: 18
        channels:
          - UCkjoHfkLEy7ZT4bA2myJ8xA
      - type: videos
        style: grid-cards
        collapse-after-rows: 2
        limit: 18
        channels:
        - UCpWAHyvsw6-Hd3FMcKIHGCA
    
    - size: small
      widgets:
      - type: releases
        repositories:
          - ollama/ollama
      - type: releases
        limit: 20
        collapse-after: 5
        repositories:
          - facebook/react
          - vuejs/core
          - vitejs/vite
          - flutter/flutter
          - vercel/next.js
          - nestjs/nest
      - type: releases
        repositories:
          - Infisical/infisical
          - supabase/supabase
          - powersync-ja/powersync-js